name: Build

on:
  push:
  pull_request:

permissions:
  checks: write
  contents: write
  id-token: write
  pages: write

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build MrKWatkins.DataStructuresAndAlgorithms
        uses: MrKWatkins/dotnet-build@main
        with:
          name: MrKWatkins.DataStructuresAndAlgorithms
